spring.application.name=lms-innovation

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/reverso
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

api.security.token.secret=sua-chave-secreta-super-dificil

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lucas.souza.nextage@gmail.com
spring.mail.password=mfrzjdubxslrxapq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Hotmart Configuration
hotmart.token=seu-token-de-verificacao-hotmart
